"""
core/report_generator.py
─────────────────────────
Meeting report generation for RECALL — AI Meeting Intelligence.

Generates PDF and TXT exports of processed meetings with all structured data.
"""

from __future__ import annotations

import io
import logging
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER

from core.models.meeting import Meeting
from core.models.transcript import format_timestamp

logger = logging.getLogger(__name__)


def generate_pdf_report(meeting: Meeting, summary: str) -> bytes:
    """Generate a PDF meeting report and return as bytes.

    Parameters
    ----------
    meeting : Meeting
        A fully processed Meeting object with segments, decisions, etc.
    summary : str
        The meeting summary text generated by the LLM.

    Returns
    -------
    bytes
        PDF content as bytes, suitable for st.download_button().
    """
    # Create in-memory PDF
    pdf_buffer = io.BytesIO()

    doc = SimpleDocTemplate(pdf_buffer, pagesize=letter, topMargin=0.75*inch, bottomMargin=0.75*inch)
    story = []
    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Heading1"],
        fontSize=24,
        textColor=colors.HexColor("#7c3aed"),
        spaceAfter=6,
        fontName="Helvetica-Bold",
    )
    subtitle_style = ParagraphStyle(
        "CustomSubtitle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#7070a0"),
        spaceAfter=12,
        fontName="Helvetica",
    )
    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading2"],
        fontSize=14,
        textColor=colors.HexColor("#7c3aed"),
        spaceAfter=8,
        spaceBefore=12,
        fontName="Helvetica-Bold",
    )
    normal_style = ParagraphStyle(
        "CustomNormal",
        parent=styles["Normal"],
        fontSize=10,
        spaceAfter=6,
        fontName="Helvetica",
    )

    # Title
    story.append(Paragraph("🧠 RECALL", title_style))
    story.append(Paragraph("AI Meeting Intelligence", subtitle_style))
    story.append(Spacer(1, 0.2*inch))

    # Meeting info section
    meeting_info = [
        ["Meeting Title:", meeting.title or "Untitled"],
        ["Source:", meeting.source or "Unknown"],
        ["Language:", meeting.language or "english"],
        ["Duration:", f"{meeting.duration:.1f}s" if meeting.duration else "Unknown"],
    ]
    info_table = Table(meeting_info, colWidths=[1.5*inch, 4.5*inch])
    info_table.setStyle(TableStyle([
        ("FONT", (0, 0), (-1, -1), "Helvetica", 10),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#e8e8f0")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#1a1a25")),
        ("BACKGROUND", (1, 0), (1, -1), colors.HexColor("#111118")),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 0.3*inch))

    # Summary section
    story.append(Paragraph("📋 Summary", heading_style))
    story.append(Paragraph(summary, normal_style))
    story.append(Spacer(1, 0.2*inch))

    # Key Decisions
    story.append(Paragraph("🔑 Key Decisions", heading_style))
    if meeting.decisions:
        for i, decision in enumerate(meeting.decisions, 1):
            story.append(Paragraph(f"{i}. {decision.decision}", normal_style))
    else:
        story.append(Paragraph("No decisions recorded.", normal_style))
    story.append(Spacer(1, 0.2*inch))

    # Action Items
    story.append(Paragraph("✅ Action Items", heading_style))
    if meeting.action_items:
        for i, item in enumerate(meeting.action_items, 1):
            parts = [f"{i}. {item.task}"]
            if item.owner:
                parts.append(f" | Owner: {item.owner}")
            if item.deadline:
                parts.append(f" | Deadline: {item.deadline}")
            story.append(Paragraph("".join(parts), normal_style))
    else:
        story.append(Paragraph("No action items recorded.", normal_style))
    story.append(Spacer(1, 0.2*inch))

    # Open Questions
    story.append(Paragraph("❓ Open Questions", heading_style))
    if meeting.open_questions:
        for i, question in enumerate(meeting.open_questions, 1):
            story.append(Paragraph(f"{i}. {question.question}", normal_style))
    else:
        story.append(Paragraph("No open questions recorded.", normal_style))
    story.append(Spacer(1, 0.2*inch))

    # Transcript
    story.append(PageBreak())
    story.append(Paragraph("📝 Full Transcript", heading_style))
    if meeting.segments:
        for seg in meeting.segments:
            timestamp = f"[{format_timestamp(seg.start)}]"
            content = f"{timestamp} {seg.text}"
            story.append(Paragraph(content, normal_style))
    else:
        story.append(Paragraph("No transcript available.", normal_style))

    # Build PDF
    doc.build(story)
    pdf_bytes = pdf_buffer.getvalue()
    logger.info("Generated PDF report (%d bytes)", len(pdf_bytes))
    return pdf_bytes


def generate_txt_report(meeting: Meeting, summary: str) -> str:
    """Generate a plain-text meeting report and return as string.

    Parameters
    ----------
    meeting : Meeting
        A fully processed Meeting object with segments, decisions, etc.
    summary : str
        The meeting summary text generated by the LLM.

    Returns
    -------
    str
        Plain-text report content, suitable for st.download_button().
    """
    lines = []

    # Header
    lines.append("=" * 70)
    lines.append("RECALL — AI Meeting Intelligence")
    lines.append("=" * 70)
    lines.append("")

    # Meeting info
    lines.append("MEETING")
    lines.append("-" * 70)
    lines.append(f"Title:    {meeting.title or 'Untitled'}")
    lines.append(f"Source:   {meeting.source or 'Unknown'}")
    lines.append(f"Language: {meeting.language or 'english'}")
    if meeting.duration:
        lines.append(f"Duration: {meeting.duration:.1f} seconds")
    lines.append("")

    # Summary
    lines.append("SUMMARY")
    lines.append("-" * 70)
    lines.append(summary)
    lines.append("")

    # Decisions
    lines.append("KEY DECISIONS")
    lines.append("-" * 70)
    if meeting.decisions:
        for i, decision in enumerate(meeting.decisions, 1):
            lines.append(f"{i}. {decision.decision}")
    else:
        lines.append("No decisions recorded.")
    lines.append("")

    # Action Items
    lines.append("ACTION ITEMS")
    lines.append("-" * 70)
    if meeting.action_items:
        for i, item in enumerate(meeting.action_items, 1):
            lines.append(f"{i}. Task: {item.task}")
            if item.owner:
                lines.append(f"   Owner: {item.owner}")
            if item.deadline:
                lines.append(f"   Deadline: {item.deadline}")
    else:
        lines.append("No action items recorded.")
    lines.append("")

    # Open Questions
    lines.append("OPEN QUESTIONS")
    lines.append("-" * 70)
    if meeting.open_questions:
        for i, question in enumerate(meeting.open_questions, 1):
            lines.append(f"{i}. {question.question}")
    else:
        lines.append("No open questions recorded.")
    lines.append("")

    # Transcript
    lines.append("TRANSCRIPT")
    lines.append("-" * 70)
    if meeting.segments:
        for seg in meeting.segments:
            timestamp = format_timestamp(seg.start)
            lines.append(f"[{timestamp}] {seg.text}")
    else:
        lines.append("No transcript available.")
    lines.append("")

    # Footer
    lines.append("=" * 70)
    lines.append(f"Generated: {datetime.now().isoformat()}")
    lines.append("=" * 70)

    txt_content = "\n".join(lines)
    logger.info("Generated TXT report (%d chars)", len(txt_content))
    return txt_content
