"""
core/models/meeting.py
───────────────────────
Meeting top-level model for RECALL — AI Meeting Intelligence.

Meeting is the canonical container for a single processed session.
It holds identity, provenance, and references to all extracted data.

Meeting ID
----------
Generated automatically as a UUID4 hex string.  It is the primary key
for all downstream data (ChromaDB documents, transcript segments, action
items, decisions, questions).  It is never derived from the title or
filename so it remains stable even if those change.

Duration
--------
Stored as seconds (float).  None until audio processing determines it.

Source type
-----------
SourceType distinguishes YouTube downloads from local files so the UI
and downstream code can handle provenance correctly.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field

from core.models.transcript import TranscriptSegment
from core.models.intelligence import ActionItem, Decision, OpenQuestion


class SourceType(str, Enum):
    """How the meeting audio was provided."""

    YOUTUBE = "youtube"
    LOCAL_FILE = "local_file"
    UNKNOWN = "unknown"


class Meeting(BaseModel):
    """Top-level representation of a single RECALL meeting session.

    Fields
    ------
    id : str
        UUID4 hex.  Auto-generated.  Primary key for all related data.
    title : str
        Short professional title generated by the LLM (≤8 words).
        Defaults to empty string until title generation completes.
    source : str
        The original input — YouTube URL or local file path.
    source_type : SourceType
        Whether the source was a YouTube URL or a local file.
    duration : Optional[float]
        Total meeting audio duration in seconds.  None until known.
    language : str
        User-selected transcription language ('english' or 'hinglish').
    created_at : datetime
        UTC timestamp when this Meeting object was created.

    Relationship collections (populated as pipeline stages complete)
    ---------------------------------------------------------------
    segments : list[TranscriptSegment]
        Ordered transcript segments.  Canonical transcript representation.
    action_items : list[ActionItem]
        Extracted action items.  Populated in Phase 2B.
    decisions : list[Decision]
        Extracted key decisions.  Populated in Phase 2B.
    open_questions : list[OpenQuestion]
        Extracted open questions.  Populated in Phase 2B.
    """

    id: str = Field(default_factory=lambda: __import__("uuid").uuid4().hex)
    title: str = ""
    source: str
    source_type: SourceType = SourceType.UNKNOWN
    duration: Optional[float] = None
    language: str = "english"
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    # Relationship collections — empty until populated by pipeline stages.
    segments: list[TranscriptSegment] = Field(default_factory=list)
    action_items: list[ActionItem] = Field(default_factory=list)
    decisions: list[Decision] = Field(default_factory=list)
    open_questions: list[OpenQuestion] = Field(default_factory=list)

    def plain_transcript(self) -> str:
        """Return the full transcript as a plain string.

        Convenience method used by summarizer, extractor, and RAG engine
        during the transition period before those layers consume segments
        directly.
        """
        from core.models.transcript import segments_to_text
        return segments_to_text(self.segments)

    @property
    def segment_count(self) -> int:
        return len(self.segments)

    @property
    def has_transcript(self) -> bool:
        return len(self.segments) > 0
