"""
core/models/rag_answer.py
──────────────────────────
Structured RAG response models for RECALL — AI Meeting Intelligence.

Phase 3C: evidence-grounded RAG.
The RAG engine returns not just an answer string, but a structured response
that includes both the generated answer and the transcript evidence that
supports it.

RAGEvidence
-----------
Represents a single snippet of transcript evidence that contributed to the
answer.  All evidence fields come from the actual retrieved Chroma Documents
and TranscriptSegments — the LLM cannot invent timestamps or segment IDs.

RAGAnswer
---------
The complete RAG response:
  - answer: The natural-language response to the user's question
  - evidence: List of transcript excerpts that support this answer

Deduplication
-------------
If the same TranscriptSegment appears multiple times in retrieval results
(due to sub-chunking or retrieval overlap), evidence is deduplicated by
segment_id to avoid redundant display.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class RAGEvidence(BaseModel):
    """A single piece of transcript evidence supporting an RAG answer.

    Fields
    ------
    segment_id : str
        UUID of the TranscriptSegment this evidence came from.
        Stable identity for deduplication.
    start : float
        Start timestamp in seconds (from TranscriptSegment.start).
    end : float
        End timestamp in seconds (from TranscriptSegment.end).
    text : str
        The exact transcript text (from Document.page_content).
        No paraphrasing or LLM modification.

    Notes
    -----
    - If a segment is sub-split into multiple chunks, all chunks carry
      the parent segment's segment_id, start, end via Phase 3A provenance.
    - Deduplication uses segment_id to detect and merge duplicate evidence.
    - Timestamps are ALWAYS preserved from the Chroma Document metadata,
      never derived from or influenced by the LLM answer.
    """

    segment_id: str
    start: float
    end: float
    text: str


class RAGAnswer(BaseModel):
    """A complete RAG response with answer and supporting evidence.

    Fields
    ------
    answer : str
        The natural-language answer to the user's question.
        Generated by Mistral, but must not include fabricated metadata.
    evidence : list[RAGEvidence]
        Ordered list of transcript excerpts supporting this answer.
        Empty if no relevant documents were retrieved.
        Deduplicated by segment_id to avoid redundancy.

    Notes
    -----
    - If retrieval returns 0 documents, evidence is an empty list.
    - If the LLM answer exists but no evidence exists, this indicates
      either a retrieval failure or the LLM is hallucinating without
      context.  The evidence list remains accurate regardless.
    - All evidence timestamps and segment IDs come from the actual
      retrieved Chroma Documents, NOT from the LLM output.
    """

    answer: str
    evidence: list[RAGEvidence] = Field(default_factory=list)
